name: fridge-access
description: A project for deploying an access cluster
runtime:
  name: python
  options:
    toolchain: pip
    virtualenv: venv
config:
  k8s_env:
    type: string
    description: The Kubernetes environment type (e.g. AKS, Dawn)
  azure_subscription_id:
    type: string
    description: Azure Subscription ID for the access cluster - use a dummy value when not deploying to AKS
  azure_resource_group:
    type: string
    description: Azure Resource Group for the access cluster - use a dummy value when not deploying to AKS
  azure_disk_encryption_set:
    type: string
    description: Azure Disk Encryption Set resource name for the access cluster - use a dummy value when not deploying to AKS
  tls_environment:
    type: string
    description: TLS environment for cert-manager (e.g. staging, production)
  base_fqdn:
    type: string
    description: Base FQDN for the access cluster
  admin_ip_allowlist:
    type: array
    description: List of CIDR blocks to allow access to the API proxy SSH server
    items:
      type: string
  dawn_load_balancer_ip:
    type: string
    description: Load balancer IP for Dawn access cluster - use a dummy value when not deploying to Dawn
  harbor_fqdn_prefix:
    type: string
    description: FQDN prefix for Harbor
  lets_encrypt_email:
    type: string
    description: Email for Let's Encrypt registration
  jumpbox_ssh_public_key:
    type: string
    description: Public SSH key for the private API proxy
    secret: true
  harbor_admin_password:
    type: string
    description: Harbor admin password
    secret: true
  netbird:
    value:
      hostname:
        type: string
        description: Netbird hostname for the access cluster
      management_url:
        default: "https://api.netbird.io"
        type: string
        description: Netbird management URL for the access cluster
        secret: true
      relay_server:
        default: "relay.netbird.io"
        type: string
        description: Netbird relay server for the access cluster
      setup_key:
        type: string
        description: Netbird setup key for the access cluster
        secret: true
      signal_server:
        default: "signal.netbird.io"
        type: string
        description: Netbird signal server for the access cluster
      stun_server:
        default: "stun.netbird.io"
        type: string
        description: Netbird STUN server for the access cluster
      turn_server:
        default: "turn.netbird.io"
        type: string
        description: Netbird TURN server for the access cluster
  kubernetes:context:
    value: ""
    description: Kubernetes context for the FRIDGE deployment
