name: Renovate
on:
  workflow_dispatch:
  # Runs once a month (At 06:00 on day 1 of the month)
  schedule:
    - cron: '0 6 1 * *'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v46.3.1
        with:
          configurationFile: renovate.json
          renovate-version: full
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
